@API_URL = http://localhost:5000

### HOMEPAGE
GET {{API_URL}}/

### LOGIN
POST {{API_URL}}/login
Content-Type: application/json

{
  "email": "u1@u1.com",
  "password": "u1"
}

# PROTECTED RESOURCES

### ME route
GET {{API_URL}}/me


### Users 
GET {{API_URL}}/users

### Books
GET {{API_URL}}/books

### LOGOUT
GET {{API_URL}}/logout
